/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;

public class App {


    public static void main(String[] args) throws IOException {

        URL url = new URL("http://swquotesapi.digitaljedi.dk/api/SWQuote/RandomStarWarsQuote");

            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("GET");

        int responseCode = connection.getResponseCode();

        if (responseCode != 200) {

            try {
                Gson gson = new Gson();
                //RecentQuotes quotes = new RecentQuotes("Charles Dickens", "Hello?");
                //System.out.println(quotes);
                Reader quoteReader = Files.newBufferedReader(Paths.get("src/main/resources/recentQuotes.json"));
                RecentQuotes[] numQuotes = gson.fromJson(quoteReader, RecentQuotes[].class);
                System.out.println(quotes.stringify(getRandomNumber(0, 138), numQuotes));


            } catch (Exception ex) {
                ex.printStackTrace();
            }

            } else {


                BufferedReader input = new BufferedReader(new InputStreamReader(connection.getInputStream()));
                String oneLine = input.readLine();
                StringBuffer entireStringFromResponse = new StringBuffer();

                while (oneLine != null) {
                    entireStringFromResponse.append(oneLine);
                    oneLine = input.readLine();

                }

                input.close();

                String testing = String.valueOf(entireStringFromResponse);

                Gson g = new Gson();
                StarsWarsQuote q = g.fromJson(testing, StarsWarsQuote.class);
                
                System.out.println(q);


                File infoFromInternet = new File("src/main/resources/InfoFromInternet.json");
                infoFromInternet.createNewFile();
                FileWriter infoFileWriter = new FileWriter("src/main/resources/infoFromInternet.json");
                g.toJson(q, infoFileWriter);
                infoFileWriter.close();

            }
        }


        public static int getRandomNumber ( int min, int max){
            return (int) ((Math.random() * (max - min)) + min);
        }


    }


